#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

#define configMINIMAL_STACK_SIZE 128
#define configSYSTEM_CALL_STACK_SIZE 128

#define configMAX_PRIORITIES 5
#define configMAX_SYSCALL_INTERRUPT_PRIORITY 0

#define configENFORCE_SYSTEM_CALLS_FROM_KERNEL_ONLY 1

#define configUSE_16_BIT_TICKS 1
#define configUSE_TICK_HOOK 1
#define configUSE_IDLE_HOOK 1
#define configUSE_PREEMPTION 1

#endif // FREERTOS_CONFIG_H
